//
// Created by Joe Geezer on 16/07/2022.
//

#include "Levels.h"

int level_one_tiles[TILE_ARRAY_SIZE]  =
{
        TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES,TILE_BUSHES,
        TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES, TILE_BUSHES,
        TILE_STONE_FLOOR, TILE_STONE_FLOOR, TILE_STONE_FLOOR, TILE_STONE_FLOOR, TILE_STONE_FLOOR, TILE_STONE_FLOOR_OLD, TILE_STONE_FLOOR_OLD, TILE_STONE_FLOOR_OLD, TILE_STONE_FLOOR, TILE_STONE_FLOOR, TILE_STONE_FLOOR, TILE_STONE_FLOOR,TILE_STONE_FLOOR, TILE_STONE_FLOOR, TILE_STONE_FLOOR, TILE_STONE_FLOOR,
        TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY, TILE_CLAY,
        TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER,
        TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER,
        TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER,
        TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER,
        TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_SEA, TILE_SWAMP, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER, TILE_RIVER,
};

void get_level_one_tiles(int level_one[TILE_ARRAY_SIZE], const int tiles[TILE_ARRAY_SIZE])
{
    for (int i = 0; i <= TILE_ARRAY_SIZE; i++)
    {
        level_one[i] = tiles[i];
    }
};